### ISSUE TITLE
Observed unusual scaling (up/down) activity in Karpenter even when pods are not changes

### ISSUE THREAD

**Issue by jalawala** [awslabs/karpenter#201]
Created 3 EKS managed one on-demand and 2 spot nodegroups. Tested with a sample nginx deployment. When deployment is scaled, replicas are expected to spread on 2 spot nodegroups using a custom kube scheduler.

Karpenter initially scaled the instances 1st spot nodegroup to deploy the pods. And karpenter keeps scaling up/down the instances in this 1st nodegroup even though pods are not changed.  Karpenter does not scale 2nd nodegroup for some reason.  The details are mentioned at this link https://github.com/jalawala/karpenter-aws-demo/tree/main/k8s_custom_scheduler

**Comment by ellistarn** [comment]
Since Karpenter is metrics based, the scaling behavior is all about the metric. The easiest way to debug is to observe the metric is to go look at prometheus and search `karpenter_` and your metric should show up.

There's also a 5 minute scale down delay window, which should prevent the "flapping" behavior you're talking about. 

With respect to "spreading", Karpenter isn't a scheduler, so it has no control over whether or not the pods get scheduled to the same node. All it's doing is looking at how many resources are requested by pods that were assigned to the node (by the scheduler) and then scaling up once it passes a threshhold.

Can you share your configs?

**Comment by ellistarn** [comment]
Reading a bit more into your custom scheduler. Does it set pod.spec.nodeName at some point? Assuming you're using reserved capacity, we rely on that for making calculations: https://github.com/awslabs/karpenter/blob/main/pkg/metrics/producers/reservedcapacity/producer.go#L51

**Comment by jalawala** [comment]
Thanks for the help. This is due to a minor bug in the config files. After fixing it, Karpenter is able to scale fine. We can close the issue.

**Comment by jalawala** [comment]
This is fixed after fixing a bug in the application config files
