### ISSUE TITLE
[Provisioning] Drain node before deletion

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#226]
Research drain workflow https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

Something like
- Mark node as Unschedulable
- Wait a bit
- Evict all pods
- Delete Node

**Comment by bwagner5** [comment]
I think it would be great if we could reuse https://github.com/aws/aws-node-termination-handler, no need in reinventing the wheel here. 

As far as how it would integrate is something up for debate. 

1)  NTH already handles events via EventBridge to SQS, so we could add a karpenter event that causes NTH to drain a node. NTH could even be configured to send a webhook to karpenter when it's complete for the node deletion. This would be the easiest, since all the functionality exists to do this today.
2) Functionality could be added to NTH to make it more like a proper k8s controller. Karpenter could then mark nodes as needing to be drained, NTH would see nodes tainted or labeled a certain way (or monitor the Node CRDs), drain them, and then remove the label - something like that... This seems more extensible for other termination handler components to be plugged in later if necessary. 
3) Karpenter could call NTH directly via some registered http handler... this option doesn't seem great, but could work.
