### ISSUE TITLE
Ensure AWS cloud provider provisioner correctly handles already-deleted nodes

### ISSUE THREAD

**Issue by JacobGabrielson** [awslabs/karpenter#340]
We can probably remove this todo anyway, but before I forget, does the `Delete` implementation (for AWS) correctly handle the case where it tries to delete an already-deleted node? (It should recognize this case and not consider it an error). Otherwise you can end up in a situation where the nodes never get deleted on the K8s side (i.e., the `kubeClient.Delete` will never get called because of 1 (or more) seemingly un-deletable node)?

Currently the code looks like:

```go
func (p *InstanceProvider) Terminate(ctx context.Context, nodes []*v1.Node) error {
	if len(nodes) == 0 {
		return nil
	}
	ids := p.getInstanceIDs(nodes)

	_, err := p.ec2api.TerminateInstancesWithContext(ctx, &ec2.TerminateInstancesInput{
		InstanceIds: ids,
	})
	if err != nil {
		return fmt.Errorf("terminating %d instances, %w", len(ids), err)
	}

	return nil
}
```

Which might not handle this case.

_Originally posted by @JacobGabrielson in https://github.com/awslabs/karpenter/pull/336#discussion_r607342457_

**Comment by njtran** [comment]
To test this.
I created two instances. To test the error outputs in CLI, I turned on instance protection for one of them, and attempted to delete them. It returned an error. 

```An error occurred (OperationNotPermitted) when calling the TerminateInstances operation: The instance 'instance_id_here' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.```

After turning off instance protection, I terminated one instance, resulting in this output
```
"TerminatingInstances": [
        {
            "CurrentState": {
                "Code": 32,
                "Name": "shutting-down"
            },
            "InstanceId": "instance_a",
            "PreviousState": {
                "Code": 16,
                "Name": "running"
            }
        }
]
```

Then after the first instance is terminated, I send a command to terminate both of them, resulting in this.
```
"TerminatingInstances": [
        {
            "CurrentState": {
                "Code": 32,
                "Name": "shutting-down"
            },
            "InstanceId": "instance_a",
            "PreviousState": {
                "Code": 32,
                "Name": "shutting-down"
            }
        },
        {
            "CurrentState": {
                "Code": 48,
                "Name": "terminated"
            },
            "InstanceId": "instance_b",
            "PreviousState": {
                "Code": 48,
                "Name": "terminated"
            }
        }
]
```
The second two commands did not return any error. The previous command did not return an error because instances remain in the console for [~1 hour](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html#instance-termination) after they're terminated.

Attempting to delete an instance that is not present in the console does return an error. Since our reconcile loops are run once per 5 seconds, and an instance that is terminated will remain in the console longer than Kubernetes garbage collection will cleans up a node in the APIServer, we won't ever run into this issue.
