### ISSUE TITLE
Limit instance type flexibility to some ceiling of requested resources 

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#423]
Currently, a pod with 100m could potentially run on a 96 core machine, this is unnecessary (and pollutes the logs). We should consider something along the lines of a 3x resource ceiling for instance type selection.

**Comment by bwagner5** [comment]
I'm not sure a resource ceiling is a good thing to add to Karpenter.  Currently, Karpenter uses the lowest-N instance types ([N is 20 today](https://github.com/awslabs/karpenter/blob/e5214e43b1178ce9111f5ca340bd49491c91699b/pkg/cloudprovider/aws/instance.go#L34)) based on sorted vcpus and memory of all instance types.  

If we added a resource ceiling, we would artificially constrain the set of instance type options and still have to (/should) fallback in the case of lower bound requests (rather than limiting the request, getting ICE'd, and then retrying in the worst case... or in spot's case, getting an instance that will be interrupted much sooner with no fallback).  

In the case of a single pod w/ a 100m vcpu request, if we set a ceiling at 3x, then we'd be looking for instance types w/ 300m vcpu, inevitably rounding that up to 1 vcpu which would give us 3 instance type options for x86 and 9 for arm64.  For spot, this type of artificial limit makes a bigger difference because we're using capacity-optimized. The more instance type options we give capacity-optimized, the better chances we have of getting an instance that stays around for a while. 

The ceiling actually works almost equivalently to using a lowest-N approach for moderate to large instance type requirements. But the lowest-N is more resilient and simpler code than using a ceiling calculation. I don't think log polluting is enough to warrant this change, we could just change the log to show the first 2 or so instance types and say "8 more". We only log the instance type options at the Debug level anyways.

**Comment by ellistarn** [comment]
Ok I'm sold. WDYT about moving the lowest-N to the vendor neutral code (packer.go?)

**Comment by bwagner5** [comment]
Yeah, we should definitely move lowest-N to packing. Sharing is caring :)  I can close this issue out and open a new one for moving lowest-N to packing.  Did you want to target v0.3.0 for that move as well (I can own it)?

**Comment by bwagner5** [comment]
I went ahead and created a new issue and labeled w/ `v0.3`. I'll go ahead and close this one out. Feel free to reopen for further discussion.

**Comment by ellistarn** [comment]
Great thank you!
