### ISSUE TITLE
Decouple `Cluster.Name` from `Cluster.Endpoint` and `Cluster.CABundle`

### ISSUE THREAD

**Issue by alex-berger** [awslabs/karpenter#501]
**Tell us about your request**

The [`Cluster`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L36) field in [`ProvisionerSpec`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L33) is optional, it is a pointer `*Cluster` and thus can be `nil` and is documented with `+optional`. This is not consistent with the [validation logic](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner_validation.go#L76) which requires the `Cluster` field [to be not `nil`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner_validation.go#L77). 

I guess the validation logic is biased towards the AWS provider which **requires** the [`Cluster.Name`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go) in several places:

- https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/cloudprovider/aws/securitygroups.go
- https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/cloudprovider/aws/subnets.go#L68
- https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/cloudprovider/aws/launchtemplate.go#L72
- https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/cloudprovider/aws/launchtemplate.go#L156
- ...

Even worse, having to provide the [`Cluster`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L36) config also implies that I have to provide the [`Cluster.CABundle`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L66) attribute, as the current [validation logic requires it as well](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner_validation.go#L83). This is bad, because I don't want to provide those details as I want to use the [in-cluster configuration](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) instead (see below for why). Furthermore, other cloud providers might not need a `Cluster.Name` at all in which case it would be very irritating if one has to provide a name.

Some key findings:

- `Cluster.Name` is a (AWS) provider specific configuration attribute, Kubernetes itself has no such concept like a `Cluster.Name`.
- `Cluster.Endpoint` and `Cluster.CABundle` are client connectivity configuration parameters used by the node (kubelet) to connect to the cluster.
- `Cluster.Endpoint` must be provided as it cannot be automatically deduced from the in-cluster configuration. This is because in the in-cluster configuration it is a Kubernetes Service (DNS) name (`kubernetes.default.svc`) and the node (kubelet) will not be able to resolve that internal DNS name.
- `Cluster.CABundle` can be extracted from the in-cluster configuration (`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`).

Therefore I propose that with regard to optionality, `Cluster.Name` should be decoupled from `spec.Cluster.Endpoint` and `spec.Cluster.CABundle` as they serve completely different purposes. Which would support the following use-cases:

- only `Cluster.Endpoint` is provided and controller uses the in-cluster configuration (`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`) as default value for `Cluster.CABundle`.
- only `Cluster.Endpoint` and `Cluster.Name` are provided and controller uses the in-cluster configuration as default value for `Cluster.CABundle`.
- only `Cluster.CABundle` and `Cluster.Endpoint` is provided and controller uses those parameters.
- `Cluster.Name` as well as `Cluster.CABundle` and `Cluster.Endpoint` are provided and controller uses those parameters.

**Possible Solutions (brainstorming)**

However this is implemented, it will imply that some of the validation logic is provider specific and has to be move into the provider (e.g. the AWS provider might require the `Cluster.Name` attribute while other providers might not).

- make  [`spec.Cluster`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L36) mandatory as `Cluster.Endpoint` is mandatory.
- `Cluster.Endpoint` is mandatory
- make `Cluster.CABundle` and `Cluster.Name` optional in API and let the validation logic deal with it.
- the generic, provider agnostic, validation logic should check that `Cluster.Endpoint` is not empty.
- if `Cluster.CABundle` is empty (not set) load it from the in-cluster configuration (`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`), which will ensure that the kublet will use the latest CABundle. This will enable seamless (fully automated) CA rotation without any manual intervention (no need to manually update the `Provisioner` CRD objects).
- the AWS provider specific validation logic should check that `Cluster.Name` is not-empty.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I want to deploy Karpenter, but I don't want to provide the [`Cluster.CABundle`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L66) attribute, as I want to use the in-cluster config instead. Note, I am totally find having to provide the [`Cluster.Name`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L63) and [`Cluster.Endpoint`](https://github.com/awslabs/karpenter/blob/v0.2.8/pkg/apis/provisioning/v1alpha2/provisioner.go#L69) attribute as they never changes during the lifetime of a cluster. But I don't want to provider the `Cluster.CABundle` attribute as it might change over the course of time (e.g. if the CA expires one day and is rotated). 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Thanks @alex-berger for the excellent write up. I agree with your analysis and find this to be a rough edge as well. I'm curious how other cloud providers discover things like subnets without something like cluster name, but I agree that this is an implementation detail, and we should make this optional. 

### Proposed
From your suggestions, I think this is a reasonable path forward.

- Make spec.Cluster required (not a ptr)
- Make spec.Cluster.Endpoint required
- Make spec.Cluster.Name optional
- Make spec.Cluster.CABundle optional
- Validate Cluster.Name in AWS Cloud Provider only
- If spec.Cluster.CABundle is not set, discover it from `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

### Alternative (Discover Everything w/ Constraints)
One option would be to require cloud providers to discover everything via well known labels constraints. E.g. In AWS, require users to specify a launch template that is preconfigured with cluster connectivity parameters. For subnet/security group discovery, the well known labels must be set.

- I don't like that it increases the user configuration burden
- I like that it removes an awkward and error prone dependency on aws tags for resource discovery
- I don't like that the spec loses it's self explanatory nature, and users are required to go to the docs to figure out how to configure provisioners.

### Alternative (Loosely Type Everything)
We could make a new field:
```
Provider map[string]string
```
This would enable cloud providers to require arbitrary configuration parameters. You could imagine one provider using public certs, and not needing CABundle. You could also imagine some introspection mechanism (akin to IMDS) that could be used to discover fields like cluster endpoint or name.

- This map could still be validated by cloud providers, but would require strong documentation (outside of godocs)
- I like this approach because it creates an additional hook for cloud provider flexibility 
- I don't like that it could eventually degrade to an unusable stringly-typed configuration bag
