### ISSUE TITLE
Proposal for Provisioner to be Cluster-Scoped

### ISSUE THREAD

**Issue by bwagner5** [awslabs/karpenter#510]
**Tell us about your request**
---
What do you want us to build?

> Create the notion of a truly `Default` Provisioner that is cluster scoped. This will require changing the Provisioner CRD to a non-namespaced, cluster-scoped, global CRD. If pods do not override the Provisioner via a label, then the Default provisioner will be tasked with provisioning nodes. 

--- 
**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

> Currently, provisioners "race" to provision nodes for incoming pods that did not override the provisioner. This can create surprising and non-deterministic behavior for users. For example, two provisioners operating concurrently could provision two nodes and the first one to bind will win, but the other node will need to be cleaned up resulting in wasted resources. 

> I think a more pleasant and intuitive experience is for a pod to map 1:1 w/ a provisioner. In order to enforce a 1:1 mapping, a default provisioner will need to be a catch-all for pods that do not override the provisioner. A default provisioner that is namespaced would result in **many** provisioners for no good reason. This would increase complexity and maintainability for cluster operators. 

---
**Are you currently working around this issue?**
How are you currently solving this problem?

> The current Karpenter implementation kind of acts like this in simple setups where there is 1 provisioner. There can obviously be no racing in the 1 provisioner case. The "getting started" guide suggests this setup for starting and even names the 1 provisioner "default" in the "default" namespace. 

---
**Additional context**
Anything else we should know?

> An area that needs to be explored is how a global provisioner would work for multi-tenant, namespaced clusters and clusters-of-clusters provisioning (a cluster using karpenter to provision other k8s clusters w/ karpenter).

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
https://github.com/awslabs/karpenter/issues/496 also references this. Posting for linking purposes.

**Comment by njtran** [comment]
Great start on the conversation here, Brandon. I have a couple of questions/remarks on the following paragraph:

> I think a more pleasant and intuitive experience is for a pod to map 1:1 w/ a provisioner. In order to enforce a 1:1 mapping, a default provisioner will need to be a catch-all for pods that do not override the provisioner. A default provisioner that is namespaced would result in many provisioners for no good reason. This would increase complexity and maintainability for cluster operators.

- In this example, would Karpenter be providing a default provisioner along with other provisioners that would provision pods that don't fit any existing provisioners' constraints? Or are you suggesting that we have one global default provisioner, allowing only one Provisioner in the cluster? 
- Would changing it to cluster-scoped give us the 1:1 pod to provisioner ratio if users can specify other provisioners with other names? IIUC, that would still result in race conditions and create extra nodes.
- If we want a 1:1 pod-provisioner relationship, how can we distinguish pending pods per provisioner?

**Comment by bwagner5** [comment]
> In this example, would Karpenter be providing a default provisioner along with other provisioners that would provision pods that don't fit any existing provisioners' constraints? Or are you suggesting that we have one global default provisioner, allowing only one Provisioner in the cluster?

More of the former. All pods would be provisioned w/ the cluster-scoped "default" provisioner (this can be user defined, or maybe karpenter could define a truly default experience), unless they explicitly override the provisioner via a pod label. 

> Would changing it to cluster-scoped give us the 1:1 pod to provisioner ratio if users can specify other provisioners with other names? IIUC, that would still result in race conditions and create extra nodes.

Changing to cluster-scoped doesn't necessarily give us 1:1 but I think it's required first in order to make an intuitive experience for users that doesn't violate namespace isolation. For example, we could arbitrarily define the "default/default" provisioner as the default today, but it wouldn't make much sense for it to be the default provisioner for another namespace other than default.  As far as race conditions go, the key is in the explicitness of overriding the provisioner via labels. This could be implemented more widespread by the deployer setting up a mutating webhook for a specific team (in the case of a shared cluster managed by a platform team).  The 1:1 mapping and a default provisioner also builds in a "least resistance" pattern of "less provisioners", I think.  If provisioners are allowed to race and a user goes overboard with provisioners, you can get into a lot of weird, non-deterministic scenarios like a scaled-up deployment using multiple different OS images, security groups, etc. 

> If we want a 1:1 pod-provisioner relationship, how can we distinguish pending pods per provisioner?

Pending pods that don't override a provisioner go straight to the default provisioner. Pods that do override, will get whichever provisioner they override with.

**Comment by ellistarn** [comment]
Firstly, I love this idea and think it will provide a more intuitive experience for customers. I have a few comments on the points mentioned so far.

> An area that needs to be explored is how a global provisioner would work for multi-tenant, namespaced clusters and clusters-of-clusters provisioning (a cluster using karpenter to provision other k8s clusters w/ karpenter).

The way I read this point is that a management cluster would namespace all resources related to tenant clusters, which would be a poor fit with global provisioners. I'm not too concerned about this. My expectation for a multi-tenant implementation of karpenter is that the provisioner definitions would be defined in the tenant clusters, rather than the host cluster. This has some benefits, as it would allow us to eventually remove the spec.Cluster portion of our spec, which is currently required due to Kubernetes' lack of support for cluster introspection. 

It does somewhat close the door to Provisioner resources naturally fitting into a management cluster the manages (i.e. MachineTemplates) as namespaced resources. I'm curious if we could get some comment from the Cluster API folks as to how big of an issue this would be. 

> This could be implemented more widespread by the deployer setting up a mutating webhook for a specific team (in the case of a shared cluster managed by a platform team).

It would be straightforward to support an annotation on namespaces like `karpenter.sh/provisioner-name` out of the box, so that operators can configure a specific provisioner to apply to a whole namespace of pods. This is a fairly common practice -- I've seen Istio do this. I also think we need to be super crisp in our documentation that provisioned nodes may still contained pods from namespaces that have a difference provisioner in this case. The kubescheduler may schedule pods from other namespaces to capacity launched by a different provisioner, if those pods don't have a node selector. 

I find this behavior a touch awkward. It either creates weird and unexpected behavior, or it forces us to inject *all* pods with a provisioner node label, which may be reasonably high QPS and large blast radius if our webhook suffers performance issues.
